// 《潮汐配方》TIDAL RECIPE — 水域数据模型
// 每处水域：坐标(接真实API) + 主污染叙事 + 饮品配方 + 通感映射
// 实时数据来源：Open-Meteo (marine + air-quality)，免费无需key，浏览器直连

const WATERS = [
  {
    key: "gpgp",
    name: "太平洋垃圾带",
    nameEn: "Great Pacific Garbage Patch",
    lat: 38.0, lon: -145.0,
    x: 16, y: 40, // 地图上的百分比坐标
    drink: "垃圾带·奶盖冷萃",
    base: "透明椰子水基底 + 冷萃咖啡",
    pollutant: "塑料微粒",
    pollutantEn: "Microplastics",
    hue: 190, // 基础色相（浊蓝灰）
    story: "1.8 万亿片塑料漂浮于此，99.9% 是塑料。它没有边界，也无法打捞干净——你嚼到的每一粒「椰果」，都是一片微塑料的替身。",
    fact: "79,000 吨塑料 · 面积达 160 万平方公里 · 3 倍法国",
    toppings: ["透明糖果碎（微塑料）", "椰果粒", "海盐奶盖"],
    metric: "pm10", // 用哪个实时指标驱动"污染浓度"
    metricLabel: "悬浮颗粒物 PM10",
  },
  {
    key: "gulf",
    name: "墨西哥湾死区",
    nameEn: "Gulf of Mexico Dead Zone",
    lat: 28.5, lon: -90.5,
    x: 22, y: 46,
    drink: "死区·黑糖焦油特调",
    base: "黑糖 + 焦糖厚乳",
    pollutant: "石油泄漏 + 缺氧",
    pollutantEn: "Oil spill + Hypoxia",
    hue: 25,
    story: "2010 年深水地平线泄漏 78 万立方米原油。每年夏天，化肥径流造就一片没有氧气、没有生命的「死区」。浮在你杯顶的那层焦糖油膜，就是它。",
    fact: "死区面积最大达 22,730 平方公里 · 相当于一个新泽西州",
    toppings: ["黑色竹炭浮层（油污）", "焦糖油膜", "无气泡死寂基底"],
    metric: "carbon_monoxide",
    metricLabel: "一氧化碳 CO",
  },
  {
    key: "baltic",
    name: "波罗的海死区",
    nameEn: "Baltic Sea Dead Zone",
    lat: 58.0, lon: 20.0,
    x: 52, y: 26,
    drink: "波罗的海·灰烬气泡",
    base: "灰色芝麻糊 + 苏打",
    pollutant: "富营养化缺氧",
    pollutantEn: "Eutrophication",
    hue: 210,
    story: "全球最大的人为缺氧海域之一。过量氮磷让藻类疯长、耗尽氧气，海底成了灰色的死寂荒漠。这杯没有气泡——因为那里没有生命呼吸。",
    fact: "缺氧区面积约 70,000 平方公里 · 波及 9 国海岸",
    toppings: ["灰色藻冻", "无气泡", "死寂浑浊层"],
    metric: "carbon_monoxide",
    metricLabel: "一氧化碳 CO",
  },
  {
    key: "ganges",
    name: "恒河入海口",
    nameEn: "Ganges River Mouth",
    lat: 22.0, lon: 90.0,
    x: 70, y: 45,
    drink: "恒河·浑浊奶泥",
    base: "厚重奶昔 + 姜黄",
    pollutant: "工业废水 + 重金属",
    pollutantEn: "Heavy metals",
    hue: 40,
    story: "承载 4 亿人生活的圣河，也是全球污染最重的河流之一。制革厂的铬、生活污水、火葬残余，全部汇入这片入海口。那颗金属光泽的糖珠，是铅，是铬。",
    fact: "每天约 30 亿升污水排入 · 铬含量超标数百倍",
    toppings: ["金属光泽糖珠（重金属）", "姜黄浑浊基底", "银箔"],
    metric: "pm2_5",
    metricLabel: "细颗粒物 PM2.5",
  },
  {
    key: "seto",
    name: "濑户内海",
    nameEn: "Seto Inland Sea",
    lat: 34.3, lon: 133.5,
    x: 82, y: 40,
    drink: "濑户·硫磺赤潮",
    base: "硫磺黄芒果 + 火龙果冰沙",
    pollutant: "硫化物 + 赤潮",
    pollutantEn: "Sulphur + Red tide",
    hue: 50,
    story: "曾经的「濑户内海奇迹」背后，是反复爆发的赤潮。工业硫化物染黄海水，藻华染红海面——美丽的致命红。这杯越黄，说明今天那片海的硫，越重。",
    fact: "历史赤潮年发生超 200 次 · 硫氧化物持续超标",
    toppings: ["硫磺黄基底", "血红火龙果层（赤潮）", "浑浊感"],
    metric: "sulphur_dioxide",
    metricLabel: "二氧化硫 SO₂",
  },
  {
    key: "gbrm",
    name: "大堡礁",
    nameEn: "Great Barrier Reef",
    lat: -18.0, lon: 147.0,
    x: 86, y: 62,
    drink: "大堡礁·白化苏打",
    base: "白色椰奶 + 蓝柑苏打",
    pollutant: "海水升温白化",
    pollutantEn: "Coral bleaching",
    hue: 175,
    story: "全球最大的珊瑚礁系统，正在因海水升温而大规模白化。曾经斑斓的珊瑚褪成惨白的骨骸。你手里这杯的蓝色，会随实时海温升高而褪色——温度越高，越白。",
    fact: "2016 年以来经历 5 次大规模白化 · 部分区域死亡率超 90%",
    toppings: ["白化珊瑚糖", "蓝柑渐褪层", "海温感应变色"],
    metric: "sst", // 特殊：用海表温度驱动"白化程度"
    metricLabel: "海表温度 SST",
  },
  {
    key: "med",
    name: "地中海",
    nameEn: "Mediterranean Sea",
    lat: 35.0, lon: 18.0,
    x: 50, y: 40,
    drink: "地中海·微塑料气泡",
    base: "蓝色海盐苏打 + 柠檬",
    pollutant: "塑料污染重灾区",
    pollutantEn: "Plastic hotspot",
    hue: 200,
    story: "全球塑料密度最高的海域之一，每平方公里漂浮多达 100 万片塑料碎片。这片古老文明的摇篮，如今每一朵浪花里都掺着塑料。",
    fact: "占全球海洋 1% 面积 · 却聚集 7% 的微塑料",
    toppings: ["透明糖果碎", "海盐气泡", "柠檬浮层"],
    metric: "pm10",
    metricLabel: "悬浮颗粒物 PM10",
  },
  {
    key: "bohai",
    name: "渤海湾",
    nameEn: "Bohai Bay",
    lat: 38.5, lon: 119.5,
    x: 80, y: 34,
    drink: "渤海·工业浊金",
    base: "浑金乌龙 + 稠厚奶盖",
    pollutant: "工业+石油+富营养化",
    pollutantEn: "Industrial + Oil",
    hue: 45,
    story: "半封闭内海，水体交换缓慢，环渤海工业带的排污在此沉积。石油类、无机氮、活性磷酸盐常年超标——这是离我们最近的一片浊金色的海。",
    fact: "水体交换周期长达 30-200 年 · 污染物易累积难消散",
    toppings: ["浊金基底", "工业悬浮糖珠", "稠厚奶盖"],
    metric: "pm2_5",
    metricLabel: "细颗粒物 PM2.5",
  },
];

// 实时数据 → 污染强度归一化（0-1），驱动配方视觉
function normalizeMetric(metric, value) {
  const ranges = {
    pm10: [0, 60], pm2_5: [0, 50], carbon_monoxide: [50, 250],
    sulphur_dioxide: [0, 10], nitrogen_dioxide: [0, 30], sst: [15, 32],
  };
  const [min, max] = ranges[metric] || [0, 100];
  return Math.max(0, Math.min(1, (value - min) / (max - min)));
}

if (typeof module !== "undefined") module.exports = { WATERS, normalizeMetric };
